### ISSUE TITLE
User story: navbar should adapt to whether user is logged in or not

### ISSUE THREAD

**Issue by jonthorell** [jonthorell/synth-nu-vinyl-store#14]
Epic: #1 
Epic: #5 

As a **user** I can **easily see just the options available to me** so that I **can see what options are available to me**

# Acceptance criteria:

- Acceptance criteria 1: Link to "Administration" under should only be displayed when the logged in user is a superuser or equivalent
- Acceptance criteria 2: Does not need at this point to take user role into account. Only logged in/out
- Acceptance criteria 3: The user image changes according to who is logged in

# Tasks

- [x] Task 1: Create code to check login status and only display link when logged in
- [x] Task 2: Create code to change the user icon depending on who is logged in
- [x] Task 3: Where applicable, this should be done on basis on django-group membership

**Comment by jonthorell** [comment]
Works as intended
