### ISSUE TITLE
User story: delete account

### ISSUE THREAD

**Issue by jonthorell** [jonthorell/synth-nu-vinyl-store#19]
Epic: #5 

User Story: As a **customer** I can **delete my account** so that I **can do so if I decide I no longer wants to be a customer**

# Acceptance criteria:

- Acceptance criteria 1: The user story can delete his/her own account

# Tasks

- [ ] Task 1: Add Delete account link under user menu
- [ ] Task 2: Add Delete account link on profile page
- [ ] Task 3: Create custom code to provide the functionality

**Comment by jonthorell** [comment]
Will not be implemented
