### ISSUE TITLE
User story: maintaining stock

### ISSUE THREAD

**Issue by jonthorell** [jonthorell/synth-nu-vinyl-store#20]
Epic: #3 

User Story: As **staff** I can **add/modify/delete/update products without django-admin** so that I **can make sure the site reflects what we actually sell**

# Acceptance criteria:

- Acceptance criteria 1: A staff member can do everything needed with the products table without logging into the django console

# Tasks

- [x] Task 1: Create forms for the four actions in the heading
- [x] Task 2: Add buttons for the different actions in product_details view for modify, delete, update
- [x] Task 3: Add link under user-header for add product if user logged in is a superuser
- [x] Task 4: Prepopulate the form when necessary
- [x] Task 5: Create code that does the acutal job of altering the database

**Comment by jonthorell** [comment]
Works as intended
