### ISSUE TITLE
User story: add items to a shopping bag

### ISSUE THREAD

**Issue by jonthorell** [jonthorell/synth-nu-vinyl-store#32]
Epics: 
#13 
#4

User Story: As a **customer** I can **add items to a shopping bag** so that I **can purchase the items I am interested in**

# Acceptance criteria: 

- Acceptance criteria 1: The customer can successfully add items to his shopping bag

# Tasks

- [x] Task 1: create bag app
- [x] Task 2: create bag model
- [x] Task 3: create code to display buttons to add to the bag
- [x] Task 4: create code to actually add the item to the db model

**Comment by jonthorell** [comment]
Works as intended
