### ISSUE TITLE
User story: personal profile

### ISSUE THREAD

**Issue by jonthorell** [jonthorell/synth-nu-vinyl-store#33]
Epic: #5 

User Story: As a **customer** I should **have a personal profile** so that I **can store shipping details for future need**

# Acceptance criteria:

- Acceptance criteria 1: the user has a personal profile
- Acceptance criteria 2: the profile is created automatically when the user signs up

# Tasks

- [x] Task 1: create a profile app
- [x] Task 2: create a suitable model for the profile
- [x] Task 3: Create a view that lets the user modify and view the profile

**Comment by jonthorell** [comment]
Wroks as intended
